In [9]:
import numpy as np
import matplotlib as plt
import math
from scipy.optimize import minimize
from sklearn.metrics import confusion_matrix

In [2]:
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)
print ("5 samples Iris data X = \n", X[:5][:])
print ("All Iris data y = \n", y)

5 samples Iris data X = 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
All Iris data y = 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [3]:
from sklearn.model_selection import train_test_split
#Use sklearn's library to split the data into training and testing sets with ratio 75% to 25%. 
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=0)

**First, let's do Logistic Regression using sklearn library call**

In [4]:
from sklearn.linear_model import LogisticRegression
logistic_regressor = LogisticRegression(max_iter = 500)  
# The default constructor is: 
# LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
#       intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
#       penalty='l2', random_state=None, solver='lbfgs', tol=0.0001,
#       verbose=0, warm_start=False)

In [5]:
#X is n rows of data points by 4 columns of features 
fit_class = logistic_regressor.fit(X_train, y_train)
y_predict = fit_class.predict(X_test)
print("Predicted output of all test data: \n", y_predict)
print("Target output of all test data: \n", y_test)
print("Correctly matched index of test class and predicted class: \n", y_test == y_predict)
fit_score = 100*fit_class.score(X_test, y_test)
print("Fitting score Percent: %5.1f%%" %fit_score)

Predicted output of all test data: 
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
Target output of all test data: 
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1]
Correctly matched index of test class and predicted class: 
 [ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False]
Fitting score Percent:  97.4%


In [6]:
#Let's see what the prediction probability was for each class (0, 1, or 2) for the test cases
y_test_prob = fit_class.predict_proba(X_test)
print("Prediction probability for test data P[0], P[1], P[2]: \n", y_test_prob)

Prediction probability for test data P[0], P[1], P[2]: 
 [[1.16900386e-04 5.59225152e-02 9.43960584e-01]
 [1.26288137e-02 9.60287648e-01 2.70835381e-02]
 [9.84401717e-01 1.55982438e-02 3.88276529e-08]
 [1.25769682e-06 2.34493077e-02 9.76549435e-01]
 [9.70291296e-01 2.97085396e-02 1.64479712e-07]
 [2.01021740e-06 5.98107308e-03 9.94016917e-01]
 [9.81946364e-01 1.80535652e-02 7.13021266e-08]
 [2.83382591e-03 7.47753711e-01 2.49412463e-01]
 [1.50576867e-03 7.39123010e-01 2.59371221e-01]
 [2.04958362e-02 9.35760489e-01 4.37436752e-02]
 [9.19401453e-05 1.60147786e-01 8.39760274e-01]
 [6.95964145e-03 8.10293474e-01 1.82746884e-01]
 [4.06401090e-03 7.93858710e-01 2.02077279e-01]
 [3.04873329e-03 7.60949363e-01 2.36001904e-01]
 [3.85960375e-03 7.10476370e-01 2.85664026e-01]
 [9.82833998e-01 1.71659449e-02 5.71902002e-08]
 [6.70065900e-03 7.56237486e-01 2.37061855e-01]
 [1.13767400e-02 8.44693606e-01 1.43929654e-01]
 [9.67701510e-01 3.22982725e-02 2.17328720e-07]
 [9.82908465e-01 1.70914743e-02

In [7]:
#Let's reprint above with d decimal places
d = 1
np.set_printoptions(precision=d,suppress=True) #print with d decimal places and suppress scientific notation
print("Prediction probability for 5 rows of data P[0], P[1], P[2]: \n", y_test_prob)

Prediction probability for 5 rows of data P[0], P[1], P[2]: 
 [[0.  0.1 0.9]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [1.  0.  0. ]
 [0.  0.7 0.2]
 [0.  0.7 0.3]
 [0.  0.9 0. ]
 [0.  0.2 0.8]
 [0.  0.8 0.2]
 [0.  0.8 0.2]
 [0.  0.8 0.2]
 [0.  0.7 0.3]
 [1.  0.  0. ]
 [0.  0.8 0.2]
 [0.  0.8 0.1]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.2 0.8]
 [0.  0.7 0.3]
 [0.9 0.1 0. ]
 [1.  0.  0. ]
 [0.  0.4 0.6]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.9 0.1]
 [0.1 0.9 0. ]
 [1.  0.  0. ]
 [0.  0.1 0.9]
 [0.  0.7 0.3]
 [1.  0.  0. ]
 [0.  0.4 0.6]
 [0.  0.  1. ]
 [0.  0.9 0.1]
 [0.9 0.1 0. ]
 [0.  0.3 0.7]]


In [10]:
print(confusion_matrix(y_test, y_predict))

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]])